force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Related_User__c.field-meta.xml
<CustomField>
    <fullName>Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Balance__c/Leave_Balance__c.object-meta.xml
<CustomObject>
    <label>Leave Balance</label>
    <nameField>
        <displayFormat>Leave-{0000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Balance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Balance__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Balances</relationshipLabel>
    <relationshipName>Leave_Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Balance__c/fields/Leave_Balance__c.field-meta.xml
<CustomField>
    <fullName>Leave_Balance__c</fullName>
    <label>Leave Balance</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaveBalanceLWCControler.cls
public with sharing class LeaveBalanceLWCControler {
    @AuraEnabled(cacheable=true)
    public static Leave_Balance__c getLeaveBalanceForCurrentUser() {
        List<Employee__c> emps = [
            SELECT Id
            FROM Employee__c
            WHERE Related_User__c = :UserInfo.getUserId()
            LIMIT 1
        ];
        if (emps.isEmpty()) return null;
        List<Leave_Balance__c> balances = [
            SELECT Id, Leave_Balance__c
            FROM Leave_Balance__c
            WHERE Employee__c = :emps[0].Id
            LIMIT 1
        ];
        if (balances.isEmpty()) return null;
        return balances[0];
    }
}