force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Related_User__c.field-meta.xml
<CustomField>
    <fullName>Related_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Employee_Name_E__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name_E__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <formula>(
    (Out_Time__c - In_Time__c)/ 3600000
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LastTimeEntryController.cls
public with sharing class LastTimeEntryController {
     @AuraEnabled(cacheable=true)
    public static List<Time_Entry__c> getLastFiveDaysEntries() {
        Date today = Date.today();
        Date fiveDaysAgo = Date.today().addDays(-4);
        Id currentUserId = UserInfo.getUserId();
        Employee__c empObj = [SELECT Id FROM Employee__c WHERE Related_User__c = :currentUserId LIMIT 1]; 
        List<Time_Entry__c> entries = [
            SELECT Id, Date__c, Total_Hours__c
            FROM Time_Entry__c
            WHERE Date__c >= :fiveDaysAgo
              AND Date__c <= :today
              AND Employee_Name_E__c = :empObj.Id 
            ORDER BY Date__c DESC
            LIMIT 5
        ];
        if(!entries.isEmpty()){
            return entries;
        }else {
            return null;
        }
        
    }
}