force-app/main/default/objects/Menu_Item__c/Menu_Item__c.object-meta.xml
<CustomObject>
    <label>Menu Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Menu_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non-Veg</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Main Course</fullName>
            </value>
            <value>
                <fullName>Desserts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Menu_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Menu_Item__c/Restaurant_Menu_Item__c.object-meta.xml
<CustomObject>
    <label>Restaurant Menu Item</label>
    <nameField>
        <displayFormat>No-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restaurant Menu Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Menu_Item__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
            <value>
                <fullName>Seasonal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant_Menu_Item__c/fields/Menu_Item__c.field-meta.xml
<CustomField>
    <fullName>Menu_Item__c</fullName>
    <label>Menu Item</label>
    <referenceTo>Menu_Item__c</referenceTo>
    <relationshipLabel>Restaurant Menu Items</relationshipLabel>
    <relationshipName>Restaurant_Menu_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant_Menu_Item__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Restaurant Menu Items</relationshipLabel>
    <relationshipName>Restaurant_Menu_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MenuPageController.cls
public with sharing class MenuPageController {
    //Get the food category type picklist
    @AuraEnabled(cacheable=true)
    public static List<String> getCategoryTypePickListValue(){
        List<String> picklistvalues= new List<String>();
        Schema.DescribeFieldResult fieldresult=Menu_Item__c.Category__c.getDescribe();
        List<Schema.picklistEntry> p= fieldresult.getPicklistValues();
        for(Schema.picklistEntry recordofpicklistvalue:p){
                  picklistvalues.add(recordofpicklistvalue.getValue());
        }

        return picklistvalues;
    }

    //get food menu list 
    @AuraEnabled(cacheable=true)
    public static List<Menu_Item__c> getFoodMenuList(String searchMenu,String selectCategory,Id restaurantId ){
    
        string baseQuery='Select Id,Menu_Item__r.Name,Menu_Item__r.Image__c,Price__c,A__c,Menu_Item__r.Description__c FROM Restaurant_Menu_Item__c WHERE Restaurant__c=:restaurantId';

        if(String.isNotBlank(searchMenu)){
         baseQuery += ' AND Menu_Item__r.Name LIKE \'%' + searchMenu +'%'+ '\'';
        }
        if(String.isNotBlank(selectCategory)){
            baseQuery += ' AND Menu_Item__r.Category__c = \'' + selectCategory + '\'';
        }

        return database.query(baseQuery);

    }
}