force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/Cuisine_Type__c.field-meta.xml
<CustomField>
    <fullName>Cuisine_Type__c</fullName>
    <label>Cuisine Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Mediterranean</fullName>
            </value>
            <value>
                <fullName>Fast Food</fullName>
            </value>
            <value>
                <fullName>Vegan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Restaurant_Image__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Image__c</fullName>
    <label>Restaurant Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Restaurant_Type__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Type__c</fullName>
    <label>Restaurant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>only veg</fullName>
            </value>
            <value>
                <fullName>only non-veg</fullName>
            </value>
            <value>
                <fullName>both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestaurantHomePageController.cls
public with sharing class RestaurantHomePageController {

    //Get the cuisine type picklist value
      @AuraEnabled(cacheable=true)
      public static List<String> getCuisineTypePicklistValue(){
            List<String> picklistvalues= new List<String>();
            Schema.DescribeFieldResult fieldResult=Restaurant__c.Cuisine_Type__c.getDescribe();
            List<Schema.PicklistEntry> p= fieldResult.getPicklistValues();
            for(Schema.PicklistEntry recordofPicklisstvalue:p){
                   picklistvalues.add(recordOfPicklisstvalue.getValue());
            }

            return picklistvalues;
      }

      //get the restaurant list
      @AuraEnabled(cacheable=true)
      public static List<Restaurant__c> getRestaurantList(String searchLocation,String searchRestaurant,String selectCuisine,Boolean isVegOnly){
         System.debug('isVegOnly>>' + isVegOnly);
              String baseQuery='SELECT Id,Name,	Phone__c,Rating__c,Location__c,Cuisine_Type__c,Restaurant_Image__c,Restaurant_Type__c FROM Restaurant__c WHERE Id!=null';
			
             if(String.isNotBlank(searchLocation)){
                  baseQuery+=' AND Location__c LIKE \'%' + searchLocation + '%\'';
              }
              if(String.isNotBlank(searchRestaurant)){
                  baseQuery+=' AND Name LIKE \'%' + searchRestaurant + '%\'';
              }
              if(String.isNotBlank(selectCuisine)){
                  baseQuery+=' AND Cuisine_Type__c = \'' + selectCuisine + '\'';
              }
              
        

              if(isVegOnly) {
                  System.debug('isVegOnly>>' + isVegOnly);
                  baseQuery += ' AND Restaurant_Type__c = \'only veg\'';
                }

          
              System.debug('baseQuery--->' + Database.query(baseQuery));
                return Database.query(baseQuery);
                
      }

      
    
}