force-app/main/default/objects/Claim_Audit__c/Claim_Audit__c.object-meta.xml
<CustomObject>
    <label>Claim Audit</label>
    <nameField>
        <label>Claim Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Audit__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>fraud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Audit__c/fields/Policy_Claim__c.field-meta.xml
<CustomField>
    <fullName>Policy_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Claim</label>
    <referenceTo>Policy_Claim__c</referenceTo>
    <relationshipLabel>Claim Audit</relationshipLabel>
    <relationshipName>Claim_Audit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Policy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Premium_amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_amount__c</fullName>
    <label>Premium amount</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>expired</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/Policy_Claim__c.object-meta.xml
<CustomObject>
    <label>Policy Claim</label>
    <nameField>
        <displayFormat>CLAIM-{0000}</displayFormat>
        <label>Claim number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Claim__c/fields/Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Amount__c</fullName>
    <label>Claim Amount</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Is_Fraud__c.field-meta.xml
<CustomField>
    <fullName>Is_Fraud__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Fraud</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Claim</relationshipLabel>
    <relationshipName>Policy_Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PreventClaimCreationTriggerHandler.cls
/*Name:PreventClaimCreationTriggerHandler
 *Author:Ankit Kumar
 *Description:Handler on claim trigger
 *Date:10/09/25
 */
public with sharing class PreventClaimCreationTriggerHandler {
    public static void PreventClaimCreation(List<Policy_Claim__c>listOfClaim){

      
           
       
        System.debug(listofClaim);
       
        Set<Id> setOfPolicyId=new Set<Id>();
        for(Policy_Claim__c recordClaim:listOfClaim){
             setOfPolicyId.add(recordClaim.Policy__c);
            
        }
        
        System.debug(setOfPolicyId);

        List<Policy__c> listOfPolicy=[SELECT Id,Status__c FROM Policy__c WHERE Id IN:setOfPolicyId];
        
        Map<Id,String> mapofStatus=new Map<Id,String>();
        for(Policy__c recordOfPolicy:listOfPolicy){
            mapofStatus.put(recordOfPolicy.Id,recordOfPolicy.Status__c);
        }
        for(Policy_Claim__c recordOfClaim:listOfClaim){
            if(mapofStatus.get(recordOfClaim.Policy__c)=='expired'|| mapofStatus.get(recordOfClaim.Policy__c)=='cancelled'){
                recordOfClaim.addError('Policy is Expired or Cancelled');
            }else{
                recordOfClaim.Status__c='Submitted';
            }
        }
            
      
        

     /*
     //it's not working because inbefore insert trigger ,you never queried the related object because it does not exist in dtabase
       we only know the lookup Id's.
        for(Policy_Claim__c recordClaim:listOfClaim){
            if(recordClaim.Policy__r.Status__c=='expired'|| recordClaim.Policy__r.Status__c=='cancelled'){
                recordClaim.addError('Policy is Expired or Cancelled');
            }else{
                
            }
        }
            */
            


    

    }

    //When claim is updated to approved , insert a claim audit record
    public static void insertClaimAudit(List<Policy_Claim__c>listOfClaim,Map<Id,Policy_Claim__c>mapOfClaimRecord){

       /* Map<Id,String> mapofClaimStatus=new Map<Id, String>();
        for(Policy_Claim__c recordClaim:listOfClaim){
            mapofClaimStatus.put(recordClaim.Id,recordClaim.Status__c);
        }
            */

            Map<Id,Policy_Claim__c> mapofClaim= new Map<Id,Policy_Claim__c>();
            for(Policy_Claim__c recordOfClaim:listOfClaim){
                mapOfClaim.put(recordOfClaim.Id,recordOfClaim);
            }


        //collection
        List<Claim_Audit__c> listOfClaimAudit=new List<	Claim_Audit__c>();
        for(Id idOfMap:mapOfClaim.keySet()){
            if(mapOfClaim.get(idOfMap).Status__c=='Approved' ){
                	Claim_Audit__c recordOfClaimAudit=new Claim_Audit__c();
                    recordOfClaimAudit.Policy_Claim__c=idOfMap;
                    recordOfClaimAudit.Action__c=mapofClaim.get(idOfMap).Status__c;
                    listOfClaimAudit.add(recordOfClaimAudit);
            }
             if(mapOfClaim.get(idOfMap).Status__c=='paid' && mapofClaim.get(idOfMap).Is_Fraud__c==false){
                	Claim_Audit__c recordOfClaimAudit=new Claim_Audit__c();
                     recordOfClaimAudit.Policy_Claim__c=idOfMap;
                    recordOfClaimAudit.Action__c=mapofClaim.get(idOfMap).Status__c;
                    listOfClaimAudit.add(recordOfClaimAudit);
            }
           
            
        }
        if(!listOfClaimAudit.isEmpty()){
            Database.insert(listOfClaimAudit,false);
        }
        

        
        
    }

    //If claim amount is more than 2x of policy premium amount, mark claim as is fraud = true
        public static void marksClaimAsFraud(List<Policy_Claim__c>listOfClaim){
              
        System.debug(listofClaim);
       
        Set<Id> setOfPolicyId=new Set<Id>();
        for(Policy_Claim__c recordClaim:listOfClaim){
             setOfPolicyId.add(recordClaim.Policy__c);
            
        }
         List<Policy__c> listOfPolicy=[SELECT Id,Premium_amount__c FROM Policy__c WHERE Id IN:setOfPolicyId];
        
         Map<Id,Decimal> MapofPolicy= new Map<Id,Decimal>();
          for(Policy__c recordOfPolicy:listOfPolicy){
            MapofPolicy.put(recordOfPolicy.Id,recordOfPolicy.Premium_amount__c);
        }

        for(Policy_Claim__c recordOfClaim:listOfClaim){
            if(recordOfClaim.Claim_Amount__c>2*MapofPolicy.get(recordOfClaim.Policy__c)){
                recordOfClaim.Is_Fraud__c=true;
            }
        }
    }
}